### ISSUE TITLE
Error when enabled and pods_view is missing the argument for pods_ajax_view

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods-ajax-views#2]
When Pods AJAX Views is enabled and I don't want to ajax load certain views, it throws the following error:

Missing argument 2 for Pods_AJAX_Views_Frontend::pods_view_alt_view()

Location:
wp-content/plugins/pods-ajax-views/Pods_AJAX_Views_Frontend.php:673

Call Stack:
PodsView::view()
pods_view()

**Comment by Shelob9** [comment]
How are you preventing it from using AJAX for those views?

**Comment by cspicuzza** [comment]
When I just use pods_view instead of pods_ajax_view while the plugin is enabled.

**Comment by sc0ttkclark** [comment]
Fixed in 1.1
